Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2023-11, with the labels that each got.

#75 Fix invalid `user_strike` function name
  cogs/strike.py
Labels: bug, high priority

#81 Fix messages.json Typo
  messages.json
Labels: bug, high priority

#84 Add type aliases for decorator wrappers
  cogs/_utils.py
Labels: refactor

#85 Rename core DB file
  .gitignore
  db/settings.py
Labels: good first issue, refactor

#79 Add "Joint Honours" role to list of `OPT_IN_ROLE_NAMES`
  cogs/send_get_roles_reminders.py
Labels: bug, high priority

#86 Fix multiline strings formatting
  cogs/_utils.py
  cogs/archive.py
  cogs/edit_message.py
  cogs/induct.py
  cogs/kick_no_introduction_users.py
  cogs/make_member.py
  cogs/remind_me.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/source.py
  cogs/startup.py
  cogs/stats.py
  cogs/strike.py
  config.py
  db/core/models/__init__.py
  db/core/models/utils.py
  exceptions.py
  tests/test_utils.py
  utils.py
Labels: refactor

#87 Add `poetry-check` test workflow
  .github/workflows/tests.yml
Labels: enhancement, refactor

#88 Add `--no-interaction` flag to build script (`Dockerfile`)
  Dockerfile
Labels: bug, refactor, high priority

#89 Add new workflows & simplify base steps
  .github/workflows/scripts/__init__.py
  .github/workflows/scripts/remove_invalid_tables.py
  .github/workflows/tests.yml
  CONTRIBUTING.md
  README.md
  poetry.lock
  pyproject.toml
Labels: refactor

#62 Reduce duplicated code fragments in commands
  cogs/_command_checks.py
  cogs/_utils.py
  cogs/archive.py
  cogs/command_error.py
  cogs/delete_all.py
  cogs/edit_message.py
  cogs/induct.py
  cogs/kick_no_introduction_users.py
  cogs/make_member.py
  cogs/ping.py
  cogs/remind_me.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/source.py
  cogs/startup.py
  cogs/stats.py
  cogs/strike.py
  cogs/write_roles.py
  db/core/models/__init__.py
  exceptions.py
  tests/test_utils.py
  utils.py
Labels: refactor

#91 Add shortcut accessor notes
  cogs/archive.py
  cogs/edit_message.py
  cogs/induct.py
  cogs/kick_no_introduction_users.py
  cogs/make_member.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/stats.py
  cogs/strike.py
  cogs/write_roles.py
Labels: documentation

#80 Update dependencies
  README.md
  cogs/remind_me.py
  poetry.lock
  pyproject.toml
Labels: refactor, high priority

#99 Add shield badges to README.md
  README.md
Labels: documentation

#97 Fix searching for `*.md.original` files
  .github/workflows/scripts/remove_invalid_tables.py
Labels: bug, high priority

#93 Add explicit `remove` argument to `remove_invalid_tables.py`
  .github/workflows/scripts/remove_invalid_tables.py
Labels: enhancement
