Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2023-09, with the labels that each got.

#19 Add test suite
  .github/CODEOWNERS
  .github/workflows/check-container-image-builds.yml
  .github/workflows/tests.yml
  .github/workflows/update-container-image.yml
  .gitignore
  Dockerfile
  README.md
  config.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/utils_test.py
  utils.py
Labels: refactor

#21 Fix pytest file permissions
  README.md
  tests/utils_test.py
Labels: bug

#20 Add a mention of memberships to induction message
  cogs/events.py
Labels: enhancement, good first issue

#22 Add mypy runner workflow for type-checking
  .github/workflows/tests.yml
  cogs/commands.py
  db/settings.py
  pyproject.toml
  tests/utils_test.py
Labels: refactor

#24 Notes and spelling fixes
  README.md
  cogs/commands.py
  cogs/events.py
  poetry.lock
  pyproject.toml
  tests/utils_test.py
Labels: refactor

#23 Make bot attributes self-healing using discord fetch
  cogs/commands.py
  cogs/events.py
  cogs/tasks.py
  utils.py
Labels: refactor

#25 Fix update container image workflow
  .github/workflows/update-container-image.yml
Labels: bug

#31 Typing improvements
  cogs/commands.py
  config.py
  db/core/app_config.py
  db/core/models/utils.py
  poetry.lock
  pyproject.toml
  utils.py
Labels: bug, refactor

#3 Update make_member to union membership lists
  cogs/commands.py
Labels: refactor

#30 Lint code with ruff
  .github/workflows/tests.yml
  .gitignore
  codeStyleConfig.xml
  cogs/__init__.py
  cogs/commands.py
  cogs/events.py
  cogs/tasks.py
  cogs/utils.py
  config.py
  db/__init__.py
  db/core/__init__.py
  db/core/app_config.py
  db/core/migrations/0002_rename_channel_type_discordreminder__channel_type.py
  db/core/models/__init__.py
  db/core/models/utils.py
  db/settings.py
  exceptions.py
  main.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/utils_test.py
  utils.py
Labels: refactor

#35 Remove environment variables when running tests
  tests/utils_test.py
Labels: bug

#34 Improve entrypoint to reference python files as modules
  Dockerfile
Labels: refactor

#33 Improve documentation in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#32 Improve autocomplete values for delay option in remindme command
  cogs/commands.py
Labels: enhancement

#36 Add more tests to test utils.py
  tests/utils_test.py
  utils.py
Labels: refactor

#38 Fix overly long lines
  README.md
  cogs/commands.py
  cogs/events.py
  cogs/tasks.py
  config.py
  db/core/models/__init__.py
  db/core/models/utils.py
  db/settings.py
  example.env
  exceptions.py
  pyproject.toml
  tests/utils_test.py
  utils.py
Labels: refactor

#40 Fix shell=True security issues & reference script by module
  pyproject.toml
  tests/utils_test.py
Labels: refactor

#41 Adhere to ruff's stricter linting rules
  cogs/commands.py
  cogs/events.py
  cogs/tasks.py
  cogs/utils.py
  config.py
  db/core/models/__init__.py
  db/core/models/utils.py
  exceptions.py
  main.py
  pyproject.toml
  tests/utils_test.py
  utils.py
Labels: refactor

#46 Improve documentation & links
  CONTRIBUTING.md
  README.md
Labels: documentation

#47 Do not attempt to autofix when linting with ruff
  .github/workflows/tests.yml
  pyproject.toml
Labels: refactor

#48 Log major error exceptions
  cogs/commands.py
  cogs/events.py
  config.py
  utils.py
Labels: enhancement

#50 Automatically determine command_name from send_error function context
  cogs/commands.py
  cogs/events.py
  utils.py
Labels: refactor

#49 Quick fixes
  cogs/tasks.py
  config.py
  exceptions.py
  poetry.lock
  pyproject.toml
  utils.py
Labels: bug, refactor
