Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2024-04, with the labels that each got.

#177 Make welcome messages not ping committee
  messages.json
Labels: bug, good first issue

#175 Move invite URL generation to `on_ready` event
  cogs/startup.py
  tests/test_utils.py
  utils/__init__.py
  utils/__main__.py
  utils/base_utility_function.py
  utils/generate_invite_url.py
Labels: good first issue, refactor

#179 Update dependencies & Fix linting issues
  .github/workflows/scripts/remove_invalid_tables.py
  cogs/__init__.py
  cogs/archive.py
  cogs/command_error.py
  cogs/delete_all.py
  cogs/edit_message.py
  cogs/induct.py
  cogs/kick_no_introduction_discord_members.py
  cogs/make_member.py
  cogs/ping.py
  cogs/remind_me.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/source.py
  cogs/startup.py
  cogs/stats.py
  cogs/strike.py
  cogs/write_roles.py
  config.py
  db/_settings.py
  db/core/models/__init__.py
  db/core/models/utils.py
  exceptions.py
  poetry.lock
  pyproject.toml
  tests/test_utils.py
  utils/__init__.py
  utils/command_checks.py
  utils/error_capture_decorators.py
  utils/generate_invite_url.py
  utils/message_sender_components.py
  utils/tex_bot.py
  utils/tex_bot_base_cog.py
Labels: refactor
