Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2024-05, with the labels that each got.

#180 Fix welcome messages sent multiple times bug
  Dockerfile
  cogs/induct.py
  config.py
  db/core/models/__init__.py
  db/core/models/utils.py
  main.py
  poetry.lock
  pyproject.toml
  utils/error_capture_decorators.py
Labels: bug, refactor, deployment

#184 Fix major bug with enabling/disabling kicking no-introduction members
  cogs/kick_no_introduction_discord_members.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  utils/error_capture_decorators.py
  utils/tex_bot_base_cog.py
Labels: bug, high priority

#172 Update roles messages to include starboard opt out
  messages.json
Labels: enhancement, good first issue, high priority

#188 Fix url reference to logging webhook
  cogs/strike.py
Labels: bug

#189 Add kill command
  CONTRIBUTING.md
  cogs/__init__.py
  cogs/archive.py
  cogs/command_error.py
  cogs/delete_all.py
  cogs/edit_message.py
  cogs/induct.py
  cogs/kick_no_introduction_discord_members.py
  cogs/kill.py
  cogs/make_member.py
  cogs/ping.py
  cogs/remind_me.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/source.py
  cogs/startup.py
  cogs/stats.py
  cogs/strike.py
  cogs/write_roles.py
  config.py
  db/__init__.py
  db/_settings.py
  db/core/__init__.py
  db/core/app_config.py
  db/core/models/__init__.py
  db/core/models/utils.py
  exceptions.py
  tests/__init__.py
  tests/test_utils.py
  utils/__init__.py
  utils/command_checks.py
  utils/error_capture_decorators.py
  utils/message_sender_components.py
  utils/suppress_traceback.py
  utils/tex_bot.py
  utils/tex_bot_base_cog.py
  utils/tex_bot_contexts.py
Labels: enhancement, good first issue

#193 Fix bug with retrieving audit log entries
  cogs/send_get_roles_reminders.py
Labels: bug

#194 Make kill confirm message not ephemeral
  cogs/kill.py
  cogs/ping.py
  cogs/source.py
Labels: refactor

#196 Ensure get_roles_reminders is sent even if no guest_role_received_time can be found
  cogs/send_get_roles_reminders.py
  poetry.lock
Labels: refactor

#201 Add note about why there is a seemingly superfluous check for whether the member is part of the guild
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
Labels: documentation, good first issue

#203 Update docs for kill command
  README.md
  exceptions.py
Labels: documentation, suspended

#202 Add exit call to kill command
  cogs/kill.py
  main.py
  utils/tex_bot.py
Labels: bug, deployment

#205 Add induction message command
  cogs/induct.py
Labels: enhancement, good first issue

#207 Update `pyproject.toml` with accurate Git commit names & emails
  pyproject.toml
Labels: documentation

#206 Add reactions to introduction messages
  cogs/induct.py
Labels: enhancement, good first issue

#191 Use RCFT-PyMarkdown in workflows
  .github/workflows/check-container-image-builds.yaml
  .github/workflows/scripts/__init__.py
  .github/workflows/scripts/remove_invalid_tables.py
  .github/workflows/tests.yaml
  .github/workflows/update-container-image.yaml
  Dockerfile
  messages.json
  poetry.lock
  pyproject.toml
Labels: deployment

#200 Remove `kick_no_introduction_members` task
  .env.example
  CONTRIBUTING.md
  README.md
  cogs/__init__.py
  cogs/kick_no_introduction_discord_members.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/stats.py
  config.py
  exceptions.py
  messages.json
  utils/__init__.py
  utils/tex_bot.py
Labels: refactor, high priority

#211 Use new name for ccft-pymarkdown package
  .github/workflows/tests.yaml
  poetry.lock
  pyproject.toml
Labels: refactor, high priority

#212 Improve error instance names
  cogs/induct.py
  cogs/kill.py
  cogs/strike.py
  config.py
  db/__init__.py
  utils/tex_bot.py
Labels: refactor

#214 Fix using `MessageSenderComponent` multiple times
  .gitignore
  cogs/remind_me.py
  cogs/strike.py
  utils/message_sender_components.py
Labels: bug

#219 Small fixes
  cogs/command_error.py
  cogs/induct.py
  cogs/kill.py
  cogs/make_member.py
  poetry.lock
  pyproject.toml
  utils/__init__.py
  utils/tex_bot_base_cog.py
Labels: bug, high priority, deployment

#213 Seperate `DiscordMember` database model
  cogs/induct.py
  cogs/remind_me.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/strike.py
  db/core/migrations/0007_discordmember_alter_discordmemberstrikes_options_and_more.py
  db/core/migrations/0008_auto_20240519_0015.py
  db/core/migrations/0009_auto_20240519_0020.py
  db/core/models/__init__.py
  db/core/models/managers.py
  db/core/models/utils.py
  utils/__init__.py
Labels: refactor

#224 Add delay to introduction response to prevent error
  cogs/induct.py
Labels: bug, high priority

#226 Add exception handling to role reminder message
  cogs/induct.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
Labels: bug

#229 Refactor Exceptions into their own files
  Dockerfile
  cogs/archive.py
  cogs/command_error.py
  cogs/edit_message.py
  exceptions.py
  exceptions/__init__.py
  exceptions/base.py
  exceptions/config_changes.py
  exceptions/does_not_exist.py
  exceptions/guild.py
  exceptions/messages.py
  exceptions/strike.py
  utils/tex_bot_base_cog.py
Labels: good first issue, refactor
