Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2024-07, with the labels that each got.

#243 Add audit log fail debug print out
  cogs/strike.py
Labels: refactor

#241 Add handover functions
  README.md
  cogs/__init__.py
  cogs/annual_handover_and_reset.py
  exceptions/__init__.py
  exceptions/does_not_exist.py
  utils/tex_bot.py
Labels: enhancement

#249 Fix not checking user in strike audit log filtering
  cogs/strike.py
Labels: bug, high priority

#252 Fix auto-mod strike handling and webhook retrieval
  cogs/strike.py
  utils/tex_bot.py
Labels: bug, high priority

#258 Add missing async on aiohttp context manager
  utils/tex_bot.py
Labels: bug, high priority

#255 Small Fixes
  .github/workflows/tests.yaml
  CONTRIBUTING.md
  Dockerfile
  README.md
  cogs/__init__.py
  cogs/annual_handover_and_reset.py
  cogs/archive.py
  cogs/command_error.py
  cogs/delete_all.py
  cogs/edit_message.py
  cogs/get_token_authorisation.py
  cogs/induct.py
  cogs/kill.py
  cogs/make_applicant.py
  cogs/make_member.py
  cogs/ping.py
  cogs/remind_me.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/source.py
  cogs/startup.py
  cogs/stats.py
  cogs/strike.py
  cogs/write_roles.py
  config.py
  db/core/app_config.py
  db/core/models/__init__.py
  db/core/models/managers.py
  db/core/models/utils.py
  exceptions/__init__.py
  exceptions/base.py
  exceptions/config_changes.py
  exceptions/does_not_exist.py
  exceptions/guild.py
  exceptions/messages.py
  exceptions/strike.py
  main.py
  poetry.lock
  pyproject.toml
  tests/test_utils.py
  utils/__init__.py
  utils/command_checks.py
  utils/error_capture_decorators.py
  utils/message_sender_components.py
  utils/suppress_traceback.py
  utils/tex_bot.py
  utils/tex_bot_base_cog.py
  utils/tex_bot_contexts.py
Labels: documentation, refactor, deployment, dependencies

#248 Year channel iteration command
  cogs/__init__.py
  cogs/annual_handover_and_reset.py
  exceptions/does_not_exist.py
Labels: enhancement

#263 Update dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#267 Use @override
  cogs/remind_me.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  exceptions/base.py
  exceptions/does_not_exist.py
  exceptions/guild.py
  exceptions/messages.py
  exceptions/strike.py
  utils/suppress_traceback.py
  utils/tex_bot.py
  utils/tex_bot_base_cog.py
Labels: refactor

#265 Make all loggers Final
  cogs/annual_handover_and_reset.py
  cogs/archive.py
  cogs/command_error.py
  cogs/get_token_authorisation.py
  cogs/induct.py
  cogs/kill.py
  cogs/make_applicant.py
  cogs/make_member.py
  cogs/remind_me.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/startup.py
  config.py
  db/core/models/managers.py
  utils/error_capture_decorators.py
  utils/tex_bot.py
  utils/tex_bot_base_cog.py
Labels: refactor

#264 Use relative import statements
  cogs/__init__.py
  utils/__init__.py
Labels: refactor

#269 Improve retrieval of `intro_channel`
  cogs/make_applicant.py
Labels: refactor

#271 Add workflow to push dev images
  .github/workflows/update-dev-container-image.yaml
  .github/workflows/update-prod-container-image.yaml
Labels: deployment

#273 Downgrade push-build-action
  .github/workflows/update-dev-container-image.yaml
Labels: bug, high priority, deployment

#272 Fix shutdown error
  cogs/remind_me.py
  cogs/startup.py
  utils/error_capture_decorators.py
  utils/tex_bot.py
Labels: bug, high priority

#275 Add Dependabot version checking
  .github/dependabot.yml
Labels: deployment, dependencies

#280 Improve dependabot labels
  .github/dependabot.yaml
Labels: deployment, dependencies

#268 Run ruff format on cogs
  cogs/annual_handover_and_reset.py
  cogs/command_error.py
  cogs/get_token_authorisation.py
  cogs/induct.py
  cogs/make_applicant.py
  cogs/make_member.py
  cogs/remind_me.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/startup.py
  cogs/stats.py
  cogs/strike.py
Labels: refactor

#281 Dependabot updates
  poetry.lock
  pyproject.toml
Labels: dependencies

#282 Update build-push-action to v6
  .github/workflows/check-container-image-builds.yaml
  .github/workflows/update-dev-container-image.yaml
  .github/workflows/update-prod-container-image.yaml
Labels: deployment, dependencies

#283 Fix Dependabot branches
  .github/dependabot.yaml
  .github/workflows/update-dev-container-image.yaml
Labels: deployment, dependencies

#286 Fix invalid Dependabot configuration
  .github/dependabot.yaml
Labels: bug, high priority, deployment, dependencies

#284 Format utils (Ruff)
  utils/error_capture_decorators.py
  utils/tex_bot.py
  utils/tex_bot_base_cog.py
Labels: refactor

#285 Small fixes (again)
  .github/workflows/tests.yaml
  CONTRIBUTING.md
  Dockerfile
  README.md
  cogs/__init__.py
  cogs/annual_handover_and_reset.py
  cogs/archive.py
  cogs/delete_all.py
  cogs/edit_message.py
  cogs/get_token_authorisation.py
  cogs/induct.py
  cogs/kill.py
  cogs/make_applicant.py
  cogs/make_member.py
  cogs/ping.py
  cogs/remind_me.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/source.py
  cogs/startup.py
  cogs/stats.py
  cogs/strike.py
  cogs/write_roles.py
  config.py
  db/core/app_config.py
  db/core/models/__init__.py
  db/core/models/managers.py
  db/core/models/utils.py
  exceptions/__init__.py
  exceptions/base.py
  exceptions/config_changes.py
  exceptions/does_not_exist.py
  exceptions/guild.py
  exceptions/messages.py
  main.py
  pyproject.toml
  tests/test_utils.py
  utils/__init__.py
  utils/command_checks.py
  utils/error_capture_decorators.py
  utils/message_sender_components.py
  utils/tex_bot.py
  utils/tex_bot_base_cog.py
  utils/tex_bot_contexts.py
Labels: documentation, refactor, deployment, dependencies

#290 Fix invalid setting name
  cogs/get_token_authorisation.py
Labels: bug, high priority

#296 Update aiohttp
  .gitignore
  poetry.lock
Labels: dependencies
