Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2024-11, with the labels that each got.

#210 Actions tracking
  cogs/__init__.py
  cogs/committee_actions_tracking.py
  cogs/delete_all.py
  cogs/remind_me.py
  cogs/send_introduction_reminders.py
  cogs/strike.py
  db/core/migrations/0010_assignedcommitteeaction.py
  db/core/models/__init__.py
  db/core/models/managers.py
  exceptions/__init__.py
  exceptions/committee_actions.py
  poetry.lock
Labels: enhancement

#360 Add Committee check to year channel command
  cogs/annual_handover_and_reset.py
Labels: bug, high priority

#363 Fix missing setuptools
  poetry.lock
  pyproject.toml
Labels: bug, high priority, dependencies

#355 Use Python 3.12 type alias & generic type syntax
  db/core/models/managers.py
  utils/__init__.py
Labels: refactor
