Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2024-10, with the labels that each got.

#293 Ensure Dependabot adds correct labels to pull requests
  .github/dependabot.yaml
Labels: refactor, deployment, dependencies

#345 Add Discord badge to `README.md`
  README.md
Labels: documentation, good first issue

#348 Lock Py-Cord to 2.6.0 until fix available for typing issues
  poetry.lock
  pyproject.toml
Labels: bug, dependencies
