Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2024-06, with the labels that each got.

#233 Refactor cog names
  cogs/__init__.py
  cogs/induct.py
Labels: documentation, refactor

#237 Improve consistency of confirm-button handling
  cogs/kill.py
  cogs/strike.py
Labels: refactor

#232 Create command to give applicant role
  README.md
  cogs/__init__.py
  cogs/induct.py
  cogs/make_applicant.py
  cogs/make_member.py
  exceptions/__init__.py
  exceptions/does_not_exist.py
  utils/tex_bot.py
Labels: enhancement

#238 Fix message command typo
  cogs/make_applicant.py
Labels: bug, high priority

#231 Add token checking
  cogs/__init__.py
  cogs/get_token_authorisation.py
Labels: enhancement

#242 Add `AllChannelTypes` TypeAlias to utils
  cogs/archive.py
  utils/__init__.py
  utils/tex_bot.py
Labels: refactor
