Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2025-05, with the labels that each got.

#484 Add rule to prevent co-author line length violations
  .gitlint
Labels: bug, deployment

#472 Refactor stats cog
  cogs/stats/__init__.py
  cogs/stats/counts.py
  cogs/stats/graphs.py
Labels: refactor

#462 Strike system improvements
  cogs/delete_all.py
  cogs/strike.py
Labels: enhancement

#493 Add command to display Discord server invite link
  .env.example
  cogs/__init__.py
  cogs/invite_link.py
  config.py
Labels: enhancement

#494 Fix command details
  .env.example
  cogs/make_applicant.py
  cogs/make_member.py
  cogs/ping.py
Labels: refactor

#500 Add command checks
  cogs/strike.py
Labels: bug, high priority

#503 Improve `stats` cog documentation & type annotations
  cogs/stats/__init__.py
  cogs/stats/counts.py
  cogs/stats/graphs.py
Labels: documentation, refactor
