Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2025-06, with the labels that each got.

#508 Allow committee-elect to update actions (and appear in auto-complete)
  cogs/committee_actions_tracking.py
Labels: bug, enhancement, sync

#538 Improve workflow names
  .github/workflows/check-build-deploy.yaml
  .github/workflows/pr-auto-updater.yaml
  .github/workflows/prevent-migrations-deletion.yaml
Labels: deployment

#524 Implement testing workflow changes
  .github/workflows/check-build-deploy.yaml
  pyproject.toml
  uv.lock
Labels: deployment, dependencies, sync

#543 Update ruff & fix import lint error
  config.py
  pyproject.toml
  uv.lock
Labels: refactor, dependencies

#540 Implement config improvements
  config.py
Labels: enhancement, sync

#544 Update mypy and fix errors
  cogs/committee_actions_tracking.py
  cogs/remind_me.py
  db/core/models/__init__.py
  uv.lock
Labels: dependencies

#550 Fix `NoneType` error on committee actions tracking
  cogs/committee_actions_tracking.py
Labels: bug, high priority, sync

#555 Change auto PR updater to use App token
  .github/workflows/pr-auto-updater.yaml
Labels: deployment, sync
