Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2025-02, with the labels that each got.

#404 Fix broken package version badge
  README.md
Labels: bug, documentation

#405 Ignore `@everyone` role in induction check
  utils/__init__.py
Labels: bug, high priority

#406 Use real defer method for long methods
  cogs/induct.py
  cogs/make_applicant.py
Labels: bug, high priority

#412 Add deferral and member_count command
  cogs/__init__.py
  cogs/make_member.py
Labels: enhancement

#418 Add deferral and member_count command
  cogs/__init__.py
  cogs/make_member.py
Labels: enhancement
