Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2025-07, with the labels that each got.

#556 Improve config value splitting for comma separated sets
  cogs/invite_link.py
  config.py
Labels: refactor

#537 Add everest command
  cogs/__init__.py
  cogs/everest.py
Labels: enhancement, sync

#535 Improve text_channel and member fetch from ID processing
  utils/tex_bot.py
Labels: refactor, sync

#562 Add news role on inductions
  cogs/induct.py
  cogs/make_applicant.py
Labels: enhancement, high priority, sync

#565 Implement new delete-all commands
  cogs/delete_all.py
Labels: enhancement, sync

#568 Fix too long Discord command name error
  cogs/delete_all.py
Labels: bug, high priority

#482 Implement automatic auth token checking
  cogs/__init__.py
  cogs/check_su_platform_authorisation.py
  config.py
Labels: enhancement, sync

#573 Implement strike message failover
  cogs/strike.py
Labels: enhancement, sync

#574 Fix formatting
  utils/tex_bot.py
Labels: refactor

#580 Improve `README.md`
  README.md
Labels: documentation
