Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2025-04, with the labels that each got.

#456 Fix command name
  cogs/add_users_to_threads_and_channels.py
Labels: bug, high priority

#431 Add error logging for config setup
  cogs/startup.py
  config.py
Labels: enhancement, refactor

#458 Implement fork check for release task
  .github/workflows/check-build-deploy.yaml
Labels: bug, deployment

#463 Make add-user response ephemeral
  cogs/add_users_to_threads_and_channels.py
Labels: bug, high priority

#468 Fix constant name spelling error
  cogs/make_member.py
Labels: refactor

#465 Implement DM to applicants on induction
  cogs/make_applicant.py
Labels: enhancement

#460 Implement error handling for DM messages
  cogs/strike.py
Labels: bug, enhancement

#303 Improve the archive command
  cogs/archive.py
Labels: enhancement, refactor

#469 Fix tests status badge in README
  README.md
Labels: documentation, good first issue
