Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2025-03, with the labels that each got.

#432 Add check for forks
  .github/workflows/update-dev-container-image.yaml
Labels: bug, deployment

#433 Fix dev container fork check
  .github/workflows/update-dev-container-image.yaml
Labels: bug, high priority, deployment

#420 Swap to uv & remove poetry
  .dockerignore
  .github/dependabot.yaml
  .github/renovate.json
  .github/workflows/check-build-deploy.yaml
  .github/workflows/check-container-image-builds.yaml
  .github/workflows/tests.yaml
  .github/workflows/update-dev-container-image.yaml
  .github/workflows/update-prod-container-image.yaml
  .gitignore
  .gitlint
  .hadolint.yaml
  .pre-commit-config.yaml
  .python-version
  .taplo.toml
  .yamlfmt.yaml
  CONTRIBUTING.md
  Dockerfile
  README.md
  cogs/annual_handover_and_reset.py
  cogs/archive.py
  cogs/committee_actions_tracking.py
  cogs/edit_message.py
  cogs/get_token_authorisation.py
  cogs/induct.py
  cogs/kill.py
  cogs/make_applicant.py
  cogs/make_member.py
  cogs/ping.py
  cogs/remind_me.py
  cogs/send_get_roles_reminders.py
  cogs/send_introduction_reminders.py
  cogs/source.py
  cogs/stats.py
  cogs/strike.py
  cogs/write_roles.py
  config.py
  db/core/app_config.py
  db/core/models/__init__.py
  exceptions/base.py
  messages.json
  poetry.lock
  pyproject.toml
  utils/__init__.py
  utils/command_checks.py
  utils/tex_bot.py
  utils/tex_bot_contexts.py
  uv.lock
Labels: deployment, dependencies

#441 Improve repository structure
  .gitattributes
  .pre-commit-config.yaml
  CONTRIBUTING.md
  uv.lock
Labels: deployment

#377 Threads with friends
  cogs/__init__.py
  cogs/add_users_to_threads_and_channels.py
  config.py
Labels: enhancement
