Repository CSSUoB/TeX-Bot-Py-V2, pull requests merged in 2025-09, with the labels that each got.

#619 Use channel mention in message reporting
  cogs/strike.py
Labels: enhancement

#605 Refactor membership queries
  cogs/make_member.py
  exceptions/__init__.py
  exceptions/msl.py
  utils/msl/__init__.py
  utils/msl/memberships.py
Labels: refactor, sync

#624 Fix ignored `CommandChecks` NameError
  utils/command_checks.py
Labels: bug, high priority
